FROM golang:1.20
WORKDIR /usr/local/app
COPY . .
RUN mv logic-example.toml comet.toml \
    && mv logic-example.toml logic.toml \
    && mv job-example.toml job.toml
RUN GO111MODULE=on go build -o logic cmd/logic/main.go
ENTRYPOINT ["/usr/local/app/logic"]